# Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Tüm projeleri kopyala
COPY src ./src
COPY *.sln ./

# Restore ve publish
RUN dotnet restore src/JetKasa.WebAPI/JetKasa.WebAPI.csproj
RUN dotnet publish src/JetKasa.WebAPI/JetKasa.WebAPI.csproj -c Release -o /app/out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "JetKasa.WebAPI.dll"]