name: Publish

on: 
    workflow_dispatch:
    push:
       branches: 
            -develop
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore ./backend/src/JetKasa.WebAPI/JetKasa.WebAPI.sln

    - name: Build
      run: dotnet build ./backend/src/JetKasa.WebAPI/JetKasa.WebAPI.sln --configuration Release
    - name: Publish
      run: dotnet publish ./backend/src/JetKasa.WebAPI/JetKasa.WebAPI.sln --configuration Release --no-build
